### ISSUE TITLE
where is 'index.js' ?

### ISSUE THREAD

**Issue by maicong** [justjavac/qr-ascii#2]
大神，这个不能用啊！

**Comment by justjavac** [comment]
还没发布，先占个坑

**Comment by maicong** [comment]
好的吧

**Comment by ghost** [comment]
This project haven't finished .

2017年6月1日 下午1:45，"MaiCong" <notifications@github.com>写道：

Closed #2 <https://github.com/justjavac/qr-ascii/issues/2>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/justjavac/qr-ascii/issues/2#event-1105407456>, or mute
the thread
